require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
#use_frameworks!

# cocoapods >= 1.9.0
use_frameworks! :linkage => :static

target 'FireworkSdkExample' do
  config = use_native_modules!

  use_react_native!(path: config['reactNativePath'])
  
  pod 'FirebaseCrashlytics'

  # admob
  # pod 'FireworkVideoGAMSupport', '0.1.0'
  # pod 'Google-Mobile-Ads-SDK', '8.13.0'

  # ima
  # pod 'FireworkVideoGIMASupport', '0.1.0'
  # pod 'GoogleAds-IMA-iOS-SDK', '~> 3.14.5'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.build_configurations.each do |configurations|
      configurations.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
